name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          yarn

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Test and coverage
        run: yarn test:cov

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  build:
    runs-on: ubuntu-latest
    needs: [sonarcloud]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with: 
        images: viictorivo/teste2
        tag-sha: true

    - name: QEMU
      uses: docker/setup-qemu-action@v2

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: login to Dockerhub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        
    - name: install doctl
      id: docker_build
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./dockerfile
        platforms: linux/amd64
        push: true
        cache-from: type=registry,ref=viictorivo/order-ms:latest
        cache-to: type=inline
        tags: |
          viictorivo/order-ms:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Deploy to EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.AWS_CLUSTER_NAME }}
        kubectl apply -f api-svc/configmap-api.yml
        kubectl apply -f api-svc/api-svc.yml
        kubectl apply -f api-svc/hpa.yml
        kubectl apply -f api-svc/api-deployment.yml
        






